### ISSUE TITLE
Font not rendering correctly on linux

### ISSUE THREAD

**Issue by FalcoGer** [JonnyOThan/RasterPropMonitor#12]
I'm using DemonEin's IVA pack. I get graphical glitches on linux. Mostly the font becomes large, white blocks on all of the displays which are not the RPM MFDs. The unlit indicators look fine, but when they light up, the font becomes garbage. Most of the other indicators are unreadable.
I'm running Ubuntu 20.04 LTS and am using ASET from CKAN and the latest KSP from steam (1.9.1)

- RPM from CKAN v0.31.3
- ASET Prop Pack from CKAN v1.5
- Click Through Blocker from Git v0.1.9.5
- Toolbar Controller 1.8.0-0.1.9.4 from git (whatever that means)
- Module manager from ckan v4.1.3
- A bunch of unrelated stuff

![Screenshot at 2020-05-23 11-51-50](https://user-images.githubusercontent.com/16250196/82727735-97ba3800-9cec-11ea-8a38-45175e108b56.png)

When I turn on the lights it gets worse.
I'd much appreciate a solution or fix.

Log available [here](https://drive.google.com/file/d/11duF5mD30RwX7Ra1VKqw9dtcAvnKv2sw/view?usp=sharing).
Related forum post [here](https://forum.kerbalspaceprogram.com/index.php?/topic/190737-18x-19x-rasterpropmonitor-adopted/&do=findComment&comment=3790510)

**Comment by TheRyeGuyWhoWillNowDie** [comment]
+1 on this issue, I experience it too.

**Comment by cstby** [comment]
Any fix or workaround? I'm having the same problem on Pop!_OS 20.04. I have all the dependencies installed.

**Comment by cx405** [comment]
I am also affected. This is not just some glitch, this happens on all Linux installs. I have non-English KSP and amd gpu. This can play a role.

**Comment by Sonyboi** [comment]
I got the exact same issue too. It's almost unusable, and screenshots always look bad with it. A fix would be appreciated.

**Comment by twoexem** [comment]
Will there be any fix for this in the future?

**Comment by twoexem** [comment]
@JonnyOThan Any workaround or fix for this so far? It's really annoying and not pleasant to look at

**Comment by karljans** [comment]
I am having the same issue. 

A workaround seems to be to run the game with `-force-glcore42` flag, 42 being the latest version that still works. However this makes the sky black for me...

Possibly related to OpenGL shaders? Would make sense that it influences only Linux users then, as on windows KSP defaults to DirectX.

**Comment by JonnyOThan** [comment]
I don't have a linux machine to test this, and it doesn't occur even if I force opengl mode on windows.  I'd really appreciate it if someone could step up and fix it, but I don't think it's practical for me to spend time on it (I'd mostly just be guessing, and then have to find someone willing to test it for me, and repeat).  The first thing that's probably worth trying is recompiling the shaders; I can do that as part of the next release and just hope it goes away.

**Comment by JonnyOThan** [comment]
rebuilt the shader bundles, let's hope that works.

**Comment by monomere** [comment]
I'm not sure if I should make a new issue, but the linux text rendering bug strikes again
I have the latest version of RPM (0.31.13.4) and MAS (1.3.7), and the text has the same weird rendering thing
I will try to run ksp with `-force-glcore42` to see if it fixes the issue as mentioned in the other comment. I will maybe try to clone the project and try to rebuild the shader bundles myself

**Comment by JonnyOThan** [comment]
@monomere Can you try this with only RPM and not MAS?  It's unclear from your comment which system might be responsible for rendering the text you're seeing.  RPM has rebuilt its shader bundles and MAS has not.

**Comment by monomere** [comment]
I will try, but the problem was fixed by this in MAS too, but who knows!

**Comment by monomere** [comment]
After testing, it looks like it's a MAS problem, sorry for pinging for no reason. I'm still not sure how the MAS issue was fixed, since I don't think they've rebuilt the shader bundles (and their issue was fixed by this one being fixed)
