### ISSUE TITLE
Nothing shows up for the command pods

### ISSUE THREAD

**Issue by Pixel-Gamer99** [JonnyOThan/RasterPropMonitor#13]
No command pods except the mk1 Lander can does not have the custom IVA and uses the stock IVA

**Comment by FalcoGer** [comment]
I'm pretty sure the mk1 cockpit has IVA, too.

**Comment by JonnyOThan** [comment]
The set of parts that have IVAs supported by RasterPropMonitor has been slowly replaced in the stock game.  For example RPM comes with an IVA for the mk1pod, but the basic mk1 pod in game is now the mk1pod_v2.  There are ways to get access to the old parts if you want to play with those IVAs.

If you want IVAs for all stock parts, I recommend these two packs:

 https://forum.kerbalspaceprogram.com/index.php?/topic/186715-18x-de_ivaextension-for-all-the-stock-pod-ivas/

https://forum.kerbalspaceprogram.com/index.php?/topic/187162-17xaset-iva-for-making-history-pods/
