### ISSUE TITLE
Black screen on monitors, non-responsive buttons.

### ISSUE THREAD

**Issue by RedMoikle** [JonnyOThan/RasterPropMonitor#14]
I have this mod and DE_IVAExtension installed, The monitors show up, but they are black, and none of the buttons do anything. The other buttons in the cockpit work fine, but the ones around the monitors don't work.
![IVA](https://user-images.githubusercontent.com/10142045/84700437-0f296300-af4b-11ea-983a-cb33c9cab06b.jpg)

**Comment by RedMoikle** [comment]
Correction: this is not a bug, turns out screens need power!

**Comment by pete-h-87** [comment]
And today, 4 years later, I ran into the exact same problem...  Cheers!
