### ISSUE TITLE
ROLL seems broken by KSP 1.10

### ISSUE THREAD

**Issue by TiktaalikDreaming** [JonnyOThan/RasterPropMonitor#15]
Checking with a prop I was working on and one from ASET avionics, roll seems disconnected.  Cursory check of other variables seems OK.
Using the version for 1.8-1.9, so it might just need a recompile of course.

**Comment by TiktaalikDreaming** [comment]
@TiktaalikDreaming my amateur recompile suggests it needs more than that. No rush.

**Comment by TiktaalikDreaming** [comment]
Not the variable.  It updates if I'm not looking at it.  Jump in and out of cockpit view, it's updated everytime I enter cockpit view.
I'm using the JSIVariableAnimator, same as other gauges that are working.  Apart from which variable it looks at, the only other difference with the AHI is it's got 4 animators, and the main AHI is essentially stacked, with pitch sitting on top of roll.  
Going to try removing the slip and turn indicator variablesets to see if it's the number of them

**Comment by TiktaalikDreaming** [comment]
Not the number, might be the overlapping nature.  :/

**Comment by RWOne** [comment]
I ran my 1.10, ASET as well, Navball display takes the attitude one is in when you switch into IVA, but mine has no movement at all, roll, pitch or yaw.

If I exit back to external and back in it does change to the new attitude with the same behavior.

Digital readouts are ok, speedmode switch works as well.

I hope this assists, haven't said anything on the main KSP threads as I figured some work may be needed with the version changes to the sim  :)

**Comment by wizardkitty** [comment]
I Can Confirm. Navball will work for less then 1 second then stop moving. The prograde and other markers move still.

**Comment by JohnGilb** [comment]
I've confirmed that the issue has do with the call to navBall.relativeGymbal returning stale values. I don't have a great handle yet on quaternions, but I've been looking at the disassembled InternalNavBall to see how it operates, specifically the OnUpdate method.

The following code seems to function as a replacement for calling navBall.relativeGymbal:
```
Vector3 vesselOffset = new Vector3(90f, 0f, 0f);
Vector3 gaugeOffset = new Vector3(90f, 0f, 0f);                    
var vesselOffsetRotation = Quaternion.Euler(vesselOffset);
var gaugeOffsetRotation = Quaternion.Euler(gaugeOffset);
var localRotation = vesselOffsetRotation * FlightGlobals.ship_orientation * gaugeOffsetRotation;
var bestCandidate = localRotation;
bestCandidate.w = localRotation.x;
bestCandidate.x = localRotation.w * -1;
```
I'm sure somebody with a better understanding of quaternions/rotations could probably clean this up dramatically.
