### ISSUE TITLE
RPM not registering with ModuleManager

### ISSUE THREAD

**Issue by 7ranceaddic7** [JonnyOThan/RasterPropMonitor#16]
Came across this in my KSP.log.
Wonder if this might have something to do with InFlight problems like #12 & #13

[LOG 16:13:39.349] [AddonLoader]: Instantiating addon 'RPMShaderLoader' from assembly 'RasterPropMonitor'
[LOG 16:13:39.353] [RPMShaderLoader]: Set debugLoggingEnabled to False
[LOG 16:13:39.412] [RPMShaderLoader]: Adding RPM-included font digital-7 (italic) / 32
[LOG 16:13:39.414] [RPMShaderLoader]: Adding RPM-included font digital-7 (mono italic) / 32
[LOG 16:13:39.414] [RPMShaderLoader]: Adding RPM-included font digital-7 (mono) / 32
[LOG 16:13:39.415] [RPMShaderLoader]: Adding RPM-included font digital-7 / 32
[LOG 16:13:39.418] [RPMShaderLoader]: Adding RPM-included font InconsolataGo-Bold / 32
[LOG 16:13:39.418] [RPMShaderLoader]: Adding RPM-included font InconsolataGo-Regular / 32
[LOG 16:13:39.420] [RPMShaderLoader]: Adding RPM-included font LiberationSans-Bold / 32
[LOG 16:13:39.423] [RPMShaderLoader]: Adding RPM-included font LiberationSans-Regular / 32
[LOG 16:13:39.424] [RPMShaderLoader]: Adding RPM-included font repet___ / 32
[LOG 16:13:39.424] [RPMShaderLoader]: Found 8 RPM shaders and 9 fonts.
[ERR 16:13:39.457] [RPMShaderLoader]: Unable to register with ModuleManager for database reloads

**Comment by JonnyOThan** [comment]
It would be useful if you could provide your entire ksp.log (for example I cannot determine which version of RPM, KSP, and ModuleManager you are using just from the snipped you provided).

It would also be useful if someone could check if this also occurred in KSP 1.8 or 1.9 - if it did, then it's probably benign.

I'm fairly sure that this error is related to MM's hotloading functionality, which should not affect typical users. (see https://forum.kerbalspaceprogram.com/index.php?/topic/100186-reload-part-without-restarting-ksp/)

**Comment by 7ranceaddic7** [comment]
Sorry, my bad. This is the second I did not load a log file.

Here is the latest with the same error.

KSP 1.9.1
Win
[KSP.log](https://drive.google.com/file/d/1iyMBATeBlUWTnDfZ6EwGoZJDC8wSurp4/view?usp=sharing)

**Comment by MOARdV** [comment]
FWIW, I've seen that, too.  I suspect that the interface that ModuleManager used changed some time over the last few years.  I haven't looked into it yet.

**Comment by JonnyOThan** [comment]
Fixed today
