### ISSUE TITLE
Blurry text in MFDs

### ISSUE THREAD

**Issue by tyramal** [JonnyOThan/RasterPropMonitor#28]
all video feeds and graphics look fine, but all the text is blurry and unreadable.
![image](https://user-images.githubusercontent.com/74083087/103113527-6f930e80-4618-11eb-93cf-6cce2db944fe.png)

**Comment by StoneBlue** [comment]
What is your `Texture Quality` setting at, in the Settings->Graphics UI?
IIRC, there was mention wayy back, that the setting needs to be at `HalfRes` or higher, for this issue... vOv

**Comment by Mirovesaram** [comment]
> What is your `Texture Quality` setting at, in the Settings->Graphics UI? IIRC, there was mention wayy back, that the setting needs to be at `HalfRes` or higher, to get rid of this issue... vOv

Plus a comment about, check the game's resolution is equal than the computer's resolution. So, Texture quality `Halfres` or higher *and* the resolution must be equal the computer's resolution

**Comment by JonnyOThan** [comment]
fixed in https://github.com/JonnyOThan/RasterPropMonitor/commit/fcc74d603182f577cfb5ffb31f475bbf1206c25b
