### ISSUE TITLE
HullCamVDS crash in JSIExternalCameraSelector

### ISSUE THREAD

**Issue by JonnyOThan** [JonnyOThan/RasterPropMonitor#8]
https://forum.kerbalspaceprogram.com/index.php?/topic/145633-18x-hullcam-vds-continued/&do=findComment&comment=3726465

```[LOG 18:49:47.500] PartLoader: Compiling Part 'HullCameraVDS/Parts/hc_navcam/part/hc_navcam'
[EXC 18:49:47.506] ArgumentNullException: Value cannot be null.
Parameter name: shader
    UnityEngine.Material..ctor (UnityEngine.Shader shader) (at <5aeafee3fea24f37abd1315553f2cfa6>:0)
    JSI.JSIExternalCameraSelector..cctor () (at <7709c28c56774c8aaae82c97d20bb45d>:0)
    Rethrow as TypeInitializationException: The type initializer for 'JSI.JSIExternalCameraSelector' threw an exception.
    UnityEngine.DebugLogHandler:LogException(Exception, Object)
    ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
    UnityEngine.GameObject:AddComponent(Type)
    Part:AddModule(String, Boolean)
    Part:AddModule(ConfigNode, Boolean)
    PartLoader:ParsePart(UrlConfig, ConfigNode)
    <CompileParts>d__56:MoveNext()
    UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

I believe it's from the static initialization of this member:

https://github.com/JonnyOThan/RasterPropMonitor/blob/79e74a92ee08e9ca6c6df61076b8874ada467da4/RasterPropMonitor/Auxiliary%20modules/JSIExternalCameraSelector.cs#L53

I've already fixed this in my local branch (not yet pushed), but should verify that I can repro this crash and my change fixes it.

**Comment by MOARdV** [comment]
That looks like one of the problems that cropped up with the new Unity version - I had to make similar changes in MAS.

**Comment by JonnyOThan** [comment]
Actually it looks like the original poster was using RPM v0.17, which is quite ancient.

**Comment by JonnyOThan** [comment]
Confirmed that I could repro the issue without the code in https://github.com/JonnyOThan/RasterPropMonitor/commit/d9c5edc1784f03307dc616a43a49a9acce7ba883 and that that commit fixes the problem.
