### ISSUE TITLE
Issue With The Monitors Not Showing Up

### ISSUE THREAD

**Issue by TTaxer** [JonnyOThan/RasterPropMonitor#88]
**Describe the bug**
Monitors Dont Show Up

**KSP.log file**
[KSP.log](https://github.com/JonnyOThan/RasterPropMonitor/files/10888532/KSP.log)

**To Reproduce**
for some reason it isnt working i do not know why or how to reproduce it since it has happened every time i try to download it

**Expected behavior**
What Should Happen Is The Monitors Should Show Up But Not For Me

**Screenshots**
![Screenshot 2023-03-04 155512](https://user-images.githubusercontent.com/121460190/222906860-f6daafd8-fd69-4e2a-9a7b-d920675296e9.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - 
**Additional context**
Nothin

**Comment by JonnyOThan** [comment]
You have KSA IVA Upgrade but not ASET props, which it depends on.
